### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by garcianavalon** [otalk/hark#26]
Hi!

For projects that don't use browserify is very inconvenient having to download the bundle and have it checked in in git rather that as a external dependency like other libraries. Have you considering adding bower support? Would you be interested in a pull-request with a bower.json to support bower install?

Cheers!

**Comment by latentflip** [comment]
I'm not particularly a fan of supporting bower specifically, but I believe you should be able to do this already using the http://unpkg.com url just add `"hark": "https://unpkg.com/hark@latest/hark.bundle.js`" to your bower.json `dependencies` list. (You can switch `latest` for any semver range afaik).

**Comment by xdumaine** [comment]
You don't actually have to do anything to the project to support bower. Someone just has to run `bower register` for the repo, and to get releases, you just push them as tags. Since we already have tags, I just registered it on bower. As long as each npm release comes with it's own tag (as it should), you'll continue to get bower version updates that match for free.

**Comment by garcianavalon** [comment]
Cool! Thanks :)
